config/routes.rb
Rails.application.routes.draw do
  root to: 'pictures#top'
  get 'map', to: 'pictures#map'

  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :users, only:[:new, :create, :show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :favorites, only:[:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true, length:{ maximum:100}
  validates :production_year, presence: true, numericality: { only_integer: true, greater_than: 1990, less_than: 3000 }
  validates :running_time, presence: true, numericality: { only_integer: true, greater_than: 1 }
  validates :rating, presence: true, inclusion: { in: ['G', 'PG12', 'R15+', 'R18+'], allow_blank: true }
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :content, presence: true
  validates :content, presence: true
  # validates :image, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user, dependent: :destroy
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation {email.downcase!}
  validates :name, presence: true, length: {maximum:40}
  validates :email, presence: true, length: {maximum:255}, format:{ with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
  validates :password, presence: true, length: {minimum: 6}
  has_many :pictures, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture, dependent: :destroy 
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入りに登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿のお気に入りを解除しました"
  end

  def index
    @favorite_pictures = current_user.favorites
  end
end

app/controllers/pictures_controller.rb
require 'net/http'
require 'uri'
require 'json'

class PicturesController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:destroy, :edit]

  def top
  end

  def index
    @pictures = Picture.all.order(created_at: :desc)
  end

  def new
    if params[:back]
      @picture = Picture.new(pic_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(pic_params)
    @picture.user_id = current_user.id
    if @picture.save
      #PicturesMailer.picture_mail(@picture).deliver
      redirect_to pictures_path, notice: "投稿されました！"
    else
      render :new
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id:@picture.id)
    @api_key = ENV["GOOGLE_MAP_API"]
  end

  def edit
  end

  def update
    if @picture.update(pic_params)
      redirect_to pictures_path, notice: "更新されました！"
    else
      render :edit
    end
  end

  def destroy
    @picture.destroy
      redirect_to pictures_path, notice: "削除されました！"
  end

  def confirm
    @picture = Picture.new(pic_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def map
    
    # @pictures = Picture.all.where('not latitude is null and not longitude is null')
    # @pictures = Picture.all.where.not(latitude: nil).where.not(longitude: nil)
    @pictures = Picture.all.where.not("latitude = ?", "nil").where.not("longitude = ?", "nil")
    @api_key = ENV["GOOGLE_MAP_API"]

  end

  private

  def pic_params
    params.require(:picture).permit(:content, :image, :image_cache, :latitude, :longitude)
  end

  def set_pic
    @picture = Picture.find(params[:id])
  end

  def set_user
    redirect_to pictures_path unless @picture.user_id == current_user.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      redirect_to user_path(user.id), notice: "ログインしました"
      session[:user_id] = user.id
    else
      flash.now[:alert] = "メールアドレスまたはパスワードが間違っています"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました!"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :ensure_correct_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to pictures_path(session[:user_id]), notice: "登録しました！"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @pictures = @user.favorites
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    redirect_to pictures_path unless @user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "confirm"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id:session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<%= "お気に入り一覧" %>
<% @favorite_pictures.each do |pic| %>
  <%= image_tag(pic.picture.image.url)%>
<% end %>

<p><%= link_to "一覧画面に戻る", pictures_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictures</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
            <span class="sr-only">InstaClone</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">InstaClone</a>
        </div>
        <div id="gnavi" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if logged_in? %>
              <li><%= link_to "Profile", user_path(current_user.id) %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Log in", new_session_path %></li>
            <% end %>
            <% if logged_in? %>
              <li><%= link_to "投稿一覧", pictures_path %></li>
              <li><%= link_to "地図", map_path %></li>
            <% else %>
              <li><%= link_to "投稿一覧", new_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, url: choose_new_or_edit, local: true) do |form| %>
  <% if @picture.errors.any? %>
    <div id = "error_explnation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @picture.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
       </ul>
    </div>
  <% end %>

  <div class = "pic_content">
    <%= form.label :content %>
    <%= form.text_field :content, class: "form-control" %>
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: "form-control" %>
    <%= form.label :longitude %>
  　<%= form.text_field :longitude, class: "form-control" %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit :class => "button" %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h2>以下の内容で投稿をする</h2>
  <div class="row">
    <div class="card">
      <%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
        <div class="col-xs-12 col-sm-6 col-md-3 contents card-img-top">
          <%= image_tag(@picture.image.url) %>
          <%= form.hidden_field :image_cache %><br>
        <div class="card-body">
          <p class="card-text">content:<%= @picture.content %></p>
          <%= form.hidden_field :content %>
          <p class="card-text">latitude:<%= @picture.latitude %></p>
          <%= form.hidden_field :latitude, class: "form-control" %>
          <p class="card-text">longitude:<%= @picture.longitude %></p>
          <%= form.hidden_field :longitude, class: "form-control" %>
        </div>
        <%= form.submit :class => "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <%= form_with(model: @picture, url: new_picture_path, local: true, method: "get") do |form| %>
    <%= form.hidden_field :content %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back", :class => "btn btn-danger" %>
  <% end %>

app/views/pictures/edit.html.erb
<%= render "form" %>

app/views/pictures/index.html.erb
<div class="index_container"><h2>投稿一覧</h2>
  <% if logged_in? %>
    <p><%= link_to "投稿する", new_picture_path, class: "create_btn" %></p>
  <% else %>
    <p><%= link_to "投稿する", new_session_path, class: "create_btn" %></p>
  <% end %>
</div>
<div class="container_fluid">
  <div class="row card">
    <% @pictures.each do |picture| %>
      <div class="col-xs-12 col-sm-6 col-md-3 contents card-img-top">
      <% if false %>
        <%= image_tag(picture.image.url) if picture.image.url %>
      <% end %>
      <div class="card-body">
        <p class="card-text"><%= picture.content %></p>
        <p class="card-text"><%= picture.latitude %></p>
        <p class="card-text"><%= picture.longitude %></p>
        <%= link_to "詳細", picture_path(picture.id) %>
        <% if picture.user_id == current_user.id %>
          <%= link_to "編集", edit_picture_path(picture.id) %>
          <%= link_to "削除", picture_path(picture.id), method: :delete, data: {confirm: "本当に削除しますか？"} %>
        <% end %>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pictures/map.html.erb
<h1>地図</h1>

<div id="map" style="width: 100%; height: 500px; background-color:orange"></div>
</div>


<script>
function initMap(){
  let map = new google.maps.Map(document.getElementById('map'), {
  zoom: 15
  });
  map.panTo({lat: <%= @pictures.first.latitude%>, lng: <%= @pictures.first.longitude%>})
  
  <% @pictures.each do |picture| %>
    new google.maps.Marker({
      map: map,
      position: {lat: <%= picture.latitude %>, lng: <%= picture.longitude %>}
    })
  <% end %> 
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= @api_key %>&callback=initMap" async defer></script>

app/views/pictures/new.html.erb
<%= render "form" %>

app/views/pictures/show.html.erb
<div class="container_fluid">
  <div class="col-xs-12 col-sm-6 col-md-3 contents card-img-top">
    <%=image_tag (@picture.image.url), :size => "16x16" %>
    <div class="card-body">
      <p class="card-text"><%=@picture.user.name %><br><%=@picture.content %></p></p>
        <% unless @picture.user == current_user %>
          <% if @favorite.present? %>
            <%= link_to "お気に入りを解除する", favorite_path(id:@favorite.id), method: :delete %>
          <% else %>
            <%= link_to "お気に入りする", favorites_path(picture_id:@picture.id), method: :post %>
          <% end %>
         <% end %>
      </div>
    </div>

    <div class="col-xs-12">
      <div id="map" style="width: 100%; height: 500px; background-color:orange"></div>
    </div>
  </div>
</div>

<script>
function initMap(){
  let map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: <%= @picture.latitude %>, lng: <%= @picture.longitude %>},
  zoom: 20
  });
  marker = new google.maps.Marker({ 
      position: {lat: <%= @picture.latitude %>, lng: <%= @picture.longitude %>}, 
      map: map
   });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= @api_key %>&callback=initMap" async defer></script>

app/views/pictures/top.html.erb
<div class="container-fluid back_body">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 top_block1"><%= image_tag("jeremy-bishop-171845-unsplash.jpg", :size => "720x455") %>
      <p class="top_block2">あの子にもこの景色を見せたいな。</p><%= image_tag("liane-metzler-3301-unsplash.jpg", :size => "720x455") %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 top_block3">
      <h2><%= link_to "Insta Clone", pictures_path %></h2>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 top_block4"><%= image_tag("gabriela-parra-66015-unsplash.jpg", :size => "720x683") %>
      <h2 class="col-xs-12 col-sm-12 col-md-6 top_block5"><%= link_to "Join us", new_user_path, class: "joinus" %></h2>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 top_block6"><%= image_tag("anastasia-taioglou-214774-unsplash.jpg", :size => "720x455") %></div>
      <div class="col-xs-12 col-sm-12 col-md-6 top_block7"><%= image_tag("prottoy-hassan-283028-unsplash.jpg", :size => "720x455") %></div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 top_block6"><%= image_tag("sam-schooler-4824-unsplash.jpg", :size => "720x455") %>
        <%= image_tag("liane-metzler-3301-unsplash.jpg", :size => "720x455") %></div>
      <div class="col-xs-12 col-sm-12 col-md-6 top_block9"><p class="top_block5">みんな同じ空の下。</p></div>
      <div class="col-xs-12 col-sm-12 col-md-6 top_block4"><%= image_tag("franck-v-682614-unsplash.jpg", :size => "720x455") %>
        <h2 class="col-xs-12 col-sm-12 col-md-6 top_block10"><%= link_to "Join us", new_user_path %></h2>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row form">
  <div class="col-md-6 col-md-offset-3">
    <h2>Sign up</h2>
    <% if @user.errors.any? %>
      <div id = "error_explnation">
        <h2><%= @user.errors.count %>件のエラーがあります。</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
         </ul>
      </div>
    <% end %>
    <%= form_with(model: @user, local: true) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウントを作成する", class: "btn btn-danger btn-block" %>
    <% end %>
    <p>Do you have an account? <%= link_to "Log in", new_session_path %></p>
  </div>
</div>

app/views/users/show.html.erb
<div class="container_fluid">
  <div class="row">
    <div class="pic_content1 col-xs-12 col-sm-6 col-md-3">
      <h3><%= @user.name %>のページ</h3>
      <p>メールアドレス:<%= @user.email %></p>
      <% if logged_in? %>
        <p><%= link_to "Play with Insta?", pictures_path %></p>
      <% else %>
        <p>Play with InstaClone? <%= link_to "Log in now!", new_session_path %></p>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="card">
      <% @pictures.each do |pic| %>
        <div class="col-xs-12 col-sm-6 col-md-3 contents card-img-top">
          <%= image_tag(pic.picture.image.url) %>
            <div class="card-body">
              <p class="card-text"><%= pic.user.name %><br><%= pic.picture.content %></p>
                <%= link_to "Good Bye! My Favorite!", favorite_path(id: pic.id), method: :delete, class: "btn de" %>
             </div>
            </div>
          <% end %>
      </div>
   </div>
</div>